import React, { useState } from 'react';
import './App.css';
import { jsPDF } from "jspdf";

function App() {
  const [required, setRequired] = useState('');
  const [total, setTotal] = useState('');
  const [attended, setAttended] = useState('');
  const [result, setResult] = useState('');
  const [darkMode, setDarkMode] = useState(false);

  const calculate = () => {
    const r = parseFloat(required);
    const t = parseFloat(total);
    const a = parseFloat(attended);

    if (isNaN(r) || isNaN(t) || isNaN(a) || t === 0) {
      setResult("⚠️ Please enter valid numbers!");
      return;
    }

    const percentage = (a / t) * 100;
    const maxBunks = Math.floor((a - (r / 100) * t) / ((r / 100) - 1));

    let message = `📊 Your attendance is ${percentage.toFixed(2)}%. `;
    if (percentage >= r) {
      message += `✅ You can miss ${maxBunks} more classes.`;
    } else {
      message += `⚠️ You need to attend more classes to reach ${r}%.`;
    }

    setResult(message);
  };
  const exportPDF = () => {
  if (!result) {
    alert("Please calculate your attendance first!");
    return;
  }

  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text("📚 BunkCal Attendance Report", 20, 20);
  doc.setFontSize(12);
  doc.text(result, 20, 40);
  doc.text(`Generated by Mallikarjun Patil ❤️`, 20, 60);

  doc.save("attendance_report.pdf");
};


  return (
    <div className={`container ${darkMode ? 'dark' : ''}`}>
      <div className="card">
        <button className="toggle-mode" onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? '☀️ Light Mode' : '🌙 Dark Mode'}
        </button>

        <img src="/mascot.png" alt="Mascot" className="mascot" />

        <h1>BunkCal 🎓</h1>
        <p>Bunk Classes Tension Free</p>

        <input
          type="number"
          placeholder="Required % (e.g. 75)"
          value={required}
          onChange={(e) => setRequired(e.target.value)}
        />
        <input
          type="number"
          placeholder="Total Classes"
          value={total}
          onChange={(e) => setTotal(e.target.value)}
        />
        <input
          type="number"
          placeholder="Attended Classes"
          value={attended}
          onChange={(e) => setAttended(e.target.value)}
        />

        <button onClick={calculate}>Calculate Attendance</button>
       <button onClick={exportPDF}>📥 Download as PDF</button>

        {result && <div className="result">{result}</div>}

        <footer>Created by <strong>Mallikarjun Patil</strong> 💡</footer>
      </div>
    </div>
  );
  

}

export default App;

